package com.example.util.enumData;

public enum Post {
	MEMBER,
    NATIONAL_PRESIDENT,
    VICE_PRESIDENT,
    TREASURER,
    GENERAL_SECRETARY,
    PROJECT_MANAGER,
    ASSISTANT_TREASURER,
    DEPUTY_SECRETARY_GENERAL,
    R_D_MANAGER,
    LOGISTICS_MANAGER,
    TRAINING_MANAGER,
    OPPORTUNITIES_INTERNSHIPS_MANAGER

}
